; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "TAgStore"
#define MyAppVersion "2.0"
#define MyAppPublisher "MLSoft"
#define MyAppExeName "TagStore.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{214C4BA9-E8B8-4978-96FD-B5E5B44CCCAE}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={pf}\{#MyAppName}
DefaultGroupName={#MyAppName}
LicenseFile=C:\Users\manli\Documents\Lavori\Projects\2021\TagStore\License.txt
InfoBeforeFile=C:\Users\manli\Documents\Lavori\Projects\2021\TagStore\Readme.txt
OutputDir=C:\Users\manli\Documents\Lavori\Projects\2021\TagStore\inst
OutputBaseFilename=setup
SetupIconFile=C:\Users\manli\Documents\Lavori\Projects\2021\TagStore\2021Icon.ico
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "italian"; MessagesFile: "compiler:Languages\Italian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\manli\Documents\Lavori\Projects\2021\TagStore\TagStore.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\manli\Documents\Lavori\Projects\2021\TagStore\TSdata.abs"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

